### ISSUE TITLE
Читабельность

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-switch-case#1]
https://github.com/Alex-it-work/JS-switch-case/blob/459ee66fbb55ca4140d334253336b3f1680809e1/js/index.js#L48
- Тут явно читабельнее балее привычная форма, тем более тут она явно ложится хорошо при прямом соответствии конкретного значения enteredNum и дня недели.

**Comment by Alex-it-work** [comment]
а действительно)
