### ISSUE TITLE
"Critical code error!"

### ISSUE THREAD

**Issue by pecourses** [Alex-it-work/JS-switch-case#3]
https://github.com/Alex-it-work/JS-switch-case/blob/459ee66fbb55ca4140d334253336b3f1680809e1/js/index.js#L88
- -66 тоже вполне себе первая декада)

**Comment by Alex-it-work** [comment]
Шел 86 день февраля) 
Проверку и в первом и 2м случаее не делал потому что генератор чисел не мог по идее сгенерировать нечто иное, чем заданый предел. А писать дефолт для свитча у меня осталось с других языков,  вроде как правило хорошего тона
